server:
  port: 9999

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.14.244.179:3306/learn?characterEncoding=utf-8&useSSL=false&useAffectedRows=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    database: 5
    host: 106.14.244.179
    port: 6379
    connect-timeout: 60000
    jedis:
      pool:
        max-idle: 100
        min-idle: 0
        max-wait: 5000
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:/html/
    suffix: .html
    mode: HTML5
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    banner: false
